# python package
# simple pipeline to run integration tests

trigger:
- trial-int

variables:
  system.debug: "true"
  REF.DATA.HOME: "tardis-refdata"
  ref.data.github.url: "https://github.com/tardis-sn/tardis-refdata.git"
  tardis.build.dir: $(Build.Repository.LocalPath)

jobs:
  - job: report
    pool:
      vmImage: "ubuntu-latest"

    steps:
      - bash: |
          echo "##vso[task.prependpath]$CONDA/bin"
          sudo chown -R $USER $CONDA
        displayName: "Add CONDA to path"

      - bash: |
          git clone https://github.com/tardis-sn/tardis-refdata.git
        displayName: "fetch all ref-data"

      - bash: |
          sh ci-helpers/install_tardis_env.sh
        displayName: "Install TARDIS env"

      - bash: |
          source activate tardis
          python setup.py build_ext --inplace
        displayName: "Build & install TARDIS"

      - bash: |
          cd tardis-refdata/atom_data
          ls
        displayName: "Check"

      - bash: |
          source activate tardis
          export QT_API=pyqt
          sh ci-helpers/fetch_reference_data.sh
          pytest tardis --integration=azure-pipelines/integration.yml  -m integration --less-packets --generate-reference --html=report2.html
        displayName: "Run integration tests "
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: "$(Agent.BuildDirectory)/tardis/report1.html"
          artifact: "report1"
          publishLocation: "pipeline"

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: "$(Agent.BuildDirectory)/tardis/report2.html"
          artifact: "report2"
          publishLocation: "pipeline"

      - bash: |
          ls -lR /tmp
          echo
        condition: succeededOrFailed()
        displayName: "Check files in /tmp"